// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCavqftGpDaM_zyg5JN398SBeSGWNYmKsg',
    appId: '1:94878682816:web:157b2f8432f090b62f6725',
    messagingSenderId: '94878682816',
    projectId: 'flutter-connection-1b22b',
    authDomain: 'flutter-connection-1b22b.firebaseapp.com',
    storageBucket: 'flutter-connection-1b22b.appspot.com',
    measurementId: 'G-3BJG6JSRW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcl-GLkHv-pZ_qSbpsKPv7lAL63KmZn7E',
    appId: '1:94878682816:android:89b89074b1e611482f6725',
    messagingSenderId: '94878682816',
    projectId: 'flutter-connection-1b22b',
    storageBucket: 'flutter-connection-1b22b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWyRtt-I-rf3upFoQn5Kq9JtoT28m37-o',
    appId: '1:94878682816:ios:0b1cbc3fe62fd1422f6725',
    messagingSenderId: '94878682816',
    projectId: 'flutter-connection-1b22b',
    storageBucket: 'flutter-connection-1b22b.appspot.com',
    iosBundleId: 'com.example.testingproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWyRtt-I-rf3upFoQn5Kq9JtoT28m37-o',
    appId: '1:94878682816:ios:0b1cbc3fe62fd1422f6725',
    messagingSenderId: '94878682816',
    projectId: 'flutter-connection-1b22b',
    storageBucket: 'flutter-connection-1b22b.appspot.com',
    iosBundleId: 'com.example.testingproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCavqftGpDaM_zyg5JN398SBeSGWNYmKsg',
    appId: '1:94878682816:web:57bf1e375d50c4a82f6725',
    messagingSenderId: '94878682816',
    projectId: 'flutter-connection-1b22b',
    authDomain: 'flutter-connection-1b22b.firebaseapp.com',
    storageBucket: 'flutter-connection-1b22b.appspot.com',
    measurementId: 'G-6EV7VB9VQ7',
  );
}
